### ISSUE TITLE
How do I specify the PWD for bluecap?

### ISSUE THREAD

**Issue by bexelbie** [kirbyfan64/bluecap#2]
I have a bluecap capsule which I would like to have mount my PWD before running.  I've tried all forms of `pwd`, $PWD and ${PWD}.  Any advice?

**Comment by refi64** [comment]
So this is changing *very* soon (I have some WIP code to change this locally), but at the moment if you do `bluecap link capsule` and then `bluecap run .` (which loads the capsule in .bluecap), the current directory will be mounted. It also relabels the mount point recursively, which is why it doesn't mount it by default. 

The next version will just disable SELinux relabeling and mount your entire home directory, so none of this will be needed!

**Comment by bexelbie** [comment]
I need to do some more reading to better understand what the "capsule" is in this case - I must not have gotten it on my first pass

**Comment by refi64** [comment]
@bexelbie I just released 0.2, which should fix the PWD issue. Now, it will be mounted at the proper location from the wherever you are.
